# Generated by Django 5.2.9 on 2025-12-14 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'status', 'start_at'], name='clinic_appo_doctor__9d7356_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('start_at__lt', models.F('end_at'))), name='appointment_start_before_end'),
        ),
    ]
